name: Run Selenium WebDriver Tests

on:
  push:
    branches:
      - main  # or the branch you want to run the tests on
  pull_request:
    branches:
      - main  # or the branch you want to test for PRs

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Compile TypeScript code
      - name: Compile TypeScript
        run: npx tsc

      # Run Selenium WebDriver Tests
      - name: Run Tests
        run: |
          node dist/testMetaMask.js